stages:
  - build
  - examples
  - deploy

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

build_ios_base:
  stage: build
  script:
    - carthage bootstrap --cache-builds --platform iOS
    - xcodebuild test -project TripKit.xcodeproj -scheme "TripKit-iOS" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8' | xcpretty -c -r html && exit ${PIPESTATUS[0]}
    - ls -lart build/reports
  retry: 1
  cache:
    key: "$CI_BUILD_REF_NAME" # per-branch caching
    paths:
      - Carthage/Build
      - Carthage/Checkouts
  artifacts:
    paths:
    - build/reports/tests_ios.html
  tags:
    - ios

build_ios_ui:
  stage: build
  script:
    - carthage bootstrap --cache-builds --platform iOS
    - xcodebuild build -project TripKit.xcodeproj -scheme "TripKitUI-iOS" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8' | xcpretty -c -r html && exit ${PIPESTATUS[0]}
    - ls -lart build/reports
  cache:
    key: "$CI_BUILD_REF_NAME" # per-branch caching
    paths:
      - Carthage/Build
      - Carthage/Checkouts
  artifacts:
    paths:
    - build/reports/build_ios_ui.html
  tags:
    - ios

build_ios_interapp:
  stage: build
  script:
    - carthage bootstrap --cache-builds --platform iOS
    - xcodebuild build -project TripKit.xcodeproj -scheme "TripKitInterApp-iOS" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8' | xcpretty -c -r html && exit ${PIPESTATUS[0]}
    - ls -lart build/reports
  cache:
    key: "$CI_BUILD_REF_NAME" # per-branch caching
    paths:
      - Carthage/Build
      - Carthage/Checkouts
  artifacts:
    paths:
    - build/reports/build_ios_interapp.html
  tags:
    - ios

build_mac_base:
  stage: build
  script:
    - mv Cartfile.resolved Cartfile.resolved.ios
    - mv Cartfile.resolved.macos Cartfile.resolved
    - carthage bootstrap --cache-builds --platform macOS
    - xcodebuild build -project TripKit.xcodeproj -scheme "TripKit-macOS" | xcpretty -c -r html && exit ${PIPESTATUS[0]}
    - mv Cartfile.resolved Cartfile.resolved.macos
    - mv Cartfile.resolved.ios Cartfile.resolved
    - ls -lart build/reports
  cache:
    key: "$CI_BUILD_REF_NAME" # per-branch caching
    paths:
      - Carthage/Build
      - Carthage/Checkouts
  artifacts:
    paths:
    - build/reports/build_macos.html
  tags:
    - ios

build_minimap_example:
  stage: examples
  script:
    - cd Examples/MiniMap
    - pod install
    - xcodebuild build -workspace MiniMap.xcworkspace -scheme MiniMap ONLY_ACTIVE_ARCH=NO | xcpretty -c -r html && exit ${PIPESTATUS[0]}
    - ls -lart build/reports
  cache:
    key: "$CI_BUILD_REF_NAME" # per-branch caching
    paths:
      - Examples/MiniMap/Pods
  artifacts:
    paths:
    - build/reports/examples_minimap.html
  tags:
    - ios

build_cocoapodstest_example:
  stage: examples
  script:
    - cd Examples/CocoaPodsTest
    - pod install
    - xcodebuild build -workspace CocoaPodsTest.xcworkspace -scheme CocoaPodsTest ONLY_ACTIVE_ARCH=NO | xcpretty -c -r html && exit ${PIPESTATUS[0]}
    - ls -lart build/reports
  retry: 1
  cache:
    key: "$CI_BUILD_REF_NAME" # per-branch caching
    paths:
      - Examples/CocoaPodsTest/Pods
  artifacts:
    paths:
    - build/reports/examples_cocoapodstest.html
  tags:
    - ios

code_quality:
  stage: deploy
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script: 
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env SOURCE_CODE="$PWD"
        --volume "$PWD":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
  tags:
    - docker
  artifacts:
    paths: [gl-code-quality-report.json]

pages:
  stage: deploy
  script:
  - ./docs_tripkit.sh
  - ./docs_tripkitinterapp.sh
  - ./docs_tripkit_ui.sh
  - mkdir public
  - cp -r docs/TripKit public
  - cp -r docs/TripKitUI public
  - cp -r docs/TripKitInterApp public
  artifacts:
    paths:
    - public
  # only:
  # - master
