stages:
  - build
  - examples
  - deploy

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

before_script:
  - ruby --version
  - bundle install --quiet

build_ios_base:
  stage: build
  script:
    - xcodebuild test -project TripKit.xcodeproj -scheme "TripKit-iOS" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8' | xcpretty -c -r html && exit ${PIPESTATUS[0]}
  retry: 1
  artifacts:
    paths:
    - build/reports/tests.html
  tags:
    - ios

build_ios_ui:
  stage: build
  script:
    - xcodebuild build -project TripKit.xcodeproj -scheme "TripKitUI-iOS" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8' | xcpretty -c -r html && exit ${PIPESTATUS[0]}
  tags:
    - ios

build_ios_interapp:
  stage: build
  script:
    - xcodebuild build -project TripKit.xcodeproj -scheme "TripKitInterApp-iOS" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8' | xcpretty -c -r html && exit ${PIPESTATUS[0]}
  tags:
    - ios

build_mac_base:
  stage: build
  script:
    - xcodebuild build -project TripKit.xcodeproj -scheme "TripKit-macOS" | xcpretty -c && exit ${PIPESTATUS[0]}
  tags:
    - ios

build_tripkitui_example:
  stage: examples
  script:
    - xcodebuild build -project TripKit.xcodeproj -scheme TripKitUIExample -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8' | xcpretty -c && exit ${PIPESTATUS[0]}
  tags:
    - ios

build_minimap_example:
  stage: examples
  script:
    - cd Examples/MiniMap
    - pod install
    - xcodebuild build -workspace MiniMap.xcworkspace -scheme MiniMap | xcpretty -c -r html && exit ${PIPESTATUS[0]}
  cache:
    key:
      files:
        - Examples/MiniMap/Podfile
    paths:
      - Examples/MiniMap/Pods
  tags:
    - ios

    ### Not yet compatible with the switch of TripKitUI to SPM
# build_cocoapodstest_example:
#   stage: examples
#   script:
#     - cd Examples/CocoaPodsTest
#     - pod install
#     - xcodebuild build -workspace CocoaPodsTest.xcworkspace -scheme CocoaPodsTest ONLY_ACTIVE_ARCH=NO | xcpretty -c -r html && exit ${PIPESTATUS[0]}
#   retry: 1
#   cache:
#     key:
#       files:
#         - Examples/MiniMap/Podfile.lock
#     paths:
#       - Examples/CocoaPodsTest/Pods
#   tags:
#     - ios

# code_quality:
#   stage: deploy
#   image: docker:stable
#   variables:
#     DOCKER_DRIVER: overlay2
#   allow_failure: true
#   services:
#     - docker:stable-dind
#   script: 
#     - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
#     - docker run
#         --env SOURCE_CODE="$PWD"
#         --volume "$PWD":/code
#         --volume /var/run/docker.sock:/var/run/docker.sock
#         "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
#   tags:
#     - docker
#   artifacts:
#     paths: [gl-code-quality-report.json]

pages_dryrun:
  stage: deploy
  before_script:
    - brew install sourcekitten
  script:
    - ./Scripts/docs.sh
  tags:
    - ios
  artifacts:
    paths:
      - public
  except:
    - master

pages:
  stage: deploy
  before_script:
    - brew install sourcekitten
  script:
    - ./Scripts/docs.sh
  tags:
    - ios
  artifacts:
    paths:
      - public
  only:
    - master
