stages:
  - build

build_code:
  stage: build
  script:
    - export LC_ALL="en_US.UTF-8" # Fixes xcpretty (clean)
    - carthage bootstrap --cache-builds --platform iOS
    - xcodebuild test -project TripKit.xcodeproj -scheme "TripKit-iOS" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8' | xcpretty -c -r html && exit ${PIPESTATUS[0]}
  cache:
    key: "$CI_BUILD_REF_NAME" # per-branch caching
    paths:
      - Carthage/Build
      - Carthage/Checkouts
  artifacts:
    paths:
    - build/reports/tests.html
  tags:
    - ios