stages:
  - build

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

build_ios_base:
  stage: build
  script:
    - carthage bootstrap --cache-builds --platform iOS
    - xcodebuild test -project TripKit.xcodeproj -scheme "TripKit-iOS" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8' | xcpretty -c -r html && exit ${PIPESTATUS[0]}
  retry: 1
  cache:
    key: "$CI_BUILD_REF_NAME" # per-branch caching
    paths:
      - Carthage/Build/iOS
      - Carthage/Checkouts
  artifacts:
    paths:
    - build/reports/tests_ios.html
  tags:
    - ios

build_ios_ui:
  stage: build
  script:
    - carthage bootstrap --cache-builds --platform iOS
    - xcodebuild build -project TripKit.xcodeproj -scheme "TripKitUI-iOS" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8' | xcpretty -c -r html && exit ${PIPESTATUS[0]}
  cache:
    key: "$CI_BUILD_REF_NAME" # per-branch caching
    paths:
      - Carthage/Build/iOS
      - Carthage/Checkouts
  artifacts:
    paths:
    - build/reports/build_ios_ui.html
  tags:
    - ios

build_ios_interapp:
  stage: build
  script:
    - carthage bootstrap --cache-builds --platform iOS
    - xcodebuild build -project TripKit.xcodeproj -scheme "TripKitInterApp-iOS" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8' | xcpretty -c -r html && exit ${PIPESTATUS[0]}
  cache:
    key: "$CI_BUILD_REF_NAME" # per-branch caching
    paths:
      - Carthage/Build/iOS
      - Carthage/Checkouts
  artifacts:
    paths:
    - build/reports/build_ios_interapp.html
  tags:
    - ios

build_ios_bookings:
  stage: build
  script:
    - carthage bootstrap --cache-builds --platform iOS
    - xcodebuild build -project TripKit.xcodeproj -scheme "TripKitBookings-iOS" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8' | xcpretty -c -r html && exit ${PIPESTATUS[0]}
  cache:
    key: "$CI_BUILD_REF_NAME" # per-branch caching
    paths:
      - Carthage/Build/iOS
      - Carthage/Checkouts
  artifacts:
    paths:
    - build/reports/build_ios_bookings.html
  tags:
    - ios

build_mac_base:
  stage: build
  script:
    - carthage bootstrap --cache-builds --platform macOS
    - xcodebuild build -project TripKit.xcodeproj -scheme "TripKit-macOS" | xcpretty -c -r html && exit ${PIPESTATUS[0]}
  cache:
    key: "$CI_BUILD_REF_NAME" # per-branch caching
    paths:
      - Carthage/Build/Mac
      - Carthage/Checkouts
  artifacts:
    paths:
    - build/reports/build_macos.html
  tags:
    - ios
