stages:
  - build
  - code_quality

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

before_script:
  - carthage bootstrap --cache-builds

build_ios_base:
  stage: build
  script:
    - xcodebuild test -project TripKit.xcodeproj -scheme "TripKit-iOS" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8' | xcpretty -c -r html && exit ${PIPESTATUS[0]}
  retry: 2
  cache:
    key: "$CI_BUILD_REF_NAME" # per-branch caching
    paths:
      - Carthage/Build
      - Carthage/Checkouts
  artifacts:
    paths:
    - build/reports/tests_ios.html
  tags:
    - ios

build_ios_ui:
  stage: build
  script:
    - xcodebuild build -project TripKit.xcodeproj -scheme "TripKitUI-iOS" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8' | xcpretty -c -r html && exit ${PIPESTATUS[0]}
  cache:
    key: "$CI_BUILD_REF_NAME" # per-branch caching
    paths:
      - Carthage/Build
      - Carthage/Checkouts
  artifacts:
    paths:
    - build/reports/build_ios_ui.html
  tags:
    - ios

build_ios_interapp:
  stage: build
  script:
    - xcodebuild build -project TripKit.xcodeproj -scheme "TripKitInterApp-iOS" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8' | xcpretty -c -r html && exit ${PIPESTATUS[0]}
  cache:
    key: "$CI_BUILD_REF_NAME" # per-branch caching
    paths:
      - Carthage/Build
      - Carthage/Checkouts
  artifacts:
    paths:
    - build/reports/build_ios_interapp.html
  tags:
    - ios

build_ios_bookings:
  stage: build
  script:
    - xcodebuild build -project TripKit.xcodeproj -scheme "TripKitBookings-iOS" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8' | xcpretty -c -r html && exit ${PIPESTATUS[0]}
  cache:
    key: "$CI_BUILD_REF_NAME" # per-branch caching
    paths:
      - Carthage/Build
      - Carthage/Checkouts
  artifacts:
    paths:
    - build/reports/build_ios_bookings.html
  tags:
    - ios

build_mac_base:
  stage: build
  script:
    - xcodebuild build -project TripKit.xcodeproj -scheme "TripKit-macOS" | xcpretty -c -r html && exit ${PIPESTATUS[0]}
  cache:
    key: "$CI_BUILD_REF_NAME" # per-branch caching
    paths:
      - Carthage/Build
      - Carthage/Checkouts
  artifacts:
    paths:
    - build/reports/build_macos.html
  tags:
    - ios

code_quality:
  stage: code_quality
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script: 
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env SOURCE_CODE="$PWD"
        --volume "$PWD":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
  tags:
    - docker
  artifacts:
    paths: [gl-code-quality-report.json]
