stages:
  - build

build_code:
  stage: build
  script:
    - export LC_ALL="en_US.UTF-8" # Fixes cocoapods + xcpretty (clean)
    - carthage update --cache-builds
    - xcodebuild clean -workspace TripKit.xcworkspace -scheme TripKit | xcpretty -c
    - xcodebuild test -workspace TripKit.xcworkspace -scheme TripKit -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8' | xcpretty -c -r html && exit ${PIPESTATUS[0]}
  cache:
    key: "$CI_BUILD_REF_NAME" # per-branch caching
    paths:
      - Carthage/Build
      - Carthage/Checkouts
  artifacts:
    paths:
    - Project/build/reports/tests.html
  tags:
    - ios