author: SkedGo
author_url: https://skedgo.com
title: SkedGo's TripKit iOS
theme: fullwidth
output: Scripts/docs/source/TripKit

sdk: iphoneos

modules:
  - module: TripKit
  - module: TripKitUI
    build_tool_arguments:
      - -scheme
      - TripKitUI-iOS
  - module: TripKitInterApp
    build_tool_arguments:
      - -scheme
      - TripKitInterApp-iOS
merge_modules: extensions

exclude:
  - /*/TripKit/Classes/core/Loc.swift
  - /*/TripKit/Classes/core/Loc+*.swift
  - /*/TripKit/Classes/categories/*
  - /*/TripKit/vendor/*
  - /*/TripKitUI/helper/Categories/*
  - /*/TripKitUI/vendor/*

abstract: api/*.md

custom_categories:
  - name: Setup & Configuration
    children:
      - TripKit
      - TKConfig
      - TKRegion
      - TKRegionManager
      - TKServer
      - TKSettings
  - name: Trip Planning
    children:
      - TKRouter
      - TKRealTimeFetcher
      - TKWaypointRouter
      - TKTripClassifier
      - TKMetricClassifier
      - TKUIRoutingResultsViewController
      - TKUIRoutingResultsViewControllerDelegate
      - TKUIRoutingResultsCard
      - TKUIRoutingResultsCardDelegate
      - TKUIRoutingQueryInputCard
      - TKUIRoutingQueryInputCardDelegate
      - TKUITripOverviewViewController
      - TKUITripOverviewCard
      - TKUITripModeByModeViewController
      - TKUITripModeByModeViewControllerDelegate
      - TKUITripModeByModeCard
      - TKUITripModeByModePageBuilder
  - name: Timetables
    children:
      - TKUITimetableViewController
      - TKUITimetableViewControllerDelegate
      - TKUITimetableCard
      - TKUITimetableCardDelegate
      - TKUIServiceCard
  - name: Search
    children:
      - TKAppleGeocoder
      - TKCalendarManager
      - TKContactsManager
      - TKPeliasGeocoder
      - TKRegionAutocompleter
      - TKRouteAutocompleter
      - TKTripGoGeocoder
      - TKAggregateGeocoder    
      - TKUIAutocompletionViewController
      - TKUIAutocompletionViewControllerDelegate
  - name: Home Screen
    children:
      - TKUIHomeViewController
      - TKUIHomeCard
      - TKUIHomeCardSearchResultsDelegate
      - TKUIHomeComponentViewModel
      - TKUIHomeComponentContent
      - TKUIHomeComponentInput
      - TKUIHomeComponentItem
      - TKUIHomeHeaderConfiguration
      - TKUIHomeCardCustomizerItem
  - name: Notable Classes
    children:
      - TKBuzzInfoProvider
      - TKDeparturesProvider    
      - TKUICardAction
      - TKUICustomization
      - TKUIMapManager
