site_name: TripKit SDK for iOS
site_author: SkedGo Pty Ltd
site_description: Documentation of TripKit iOS - the iOS SDK of the TripGo API.

nav:
- Getting Started: index.md
- View Controllers: view-controllers.md
- F.A.Q.: faq.md
- SDK Reference:
  - TripKit: TripKit/TripKit.html
  - TripKitUI: TripKit/TripKitUI.html
  - TripKitInterApp: TripKit/TripKitInterApp.html
- API: https://developer.tripgo.com

repo_url: https://github.com/skedgo/tripkit-ios
docs_dir: source
strict: true
theme:
  name: null
  custom_dir: 'skedgo_theme'
  highlightjs: True

# Disable search, as you might expect it to search the reference, too
plugins: []

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
