source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
platform :ios, '8.0'

def shared_pods
  pod 'SGCoreKit/Core', git: 'https://github.com/skedgo/shared-ios.git', branch: 'feature/iOS10'
  pod 'SGCoreKit/Rx',   git: 'https://github.com/skedgo/shared-ios.git', branch: 'feature/iOS10'
  pod 'SGSearchKit',    git: 'https://github.com/skedgo/shared-ios.git', branch: 'feature/iOS10'
  pod 'SGUIKit',        git: 'https://github.com/skedgo/shared-ios.git', branch: 'feature/iOS10'
  pod 'SGBookingKit',   git: 'https://github.com/skedgo/shared-ios.git', branch: 'feature/iOS10'
  
  pod 'RxSwift',        branch: 'swift-3.0',  git: 'https://github.com/ReactiveX/RxSwift.git'
  pod 'RxCocoa',        branch: 'swift-3.0',  git: 'https://github.com/ReactiveX/RxSwift.git'

  # These can be removed, once their Swift3 versions are the defaults
  pod 'SwiftyJSON',     branch: 'swift3',     git: 'https://github.com/skedgo/SwiftyJSON.git'
  pod 'KeychainAccess', branch: 'swift-3.0',  git: 'https://github.com/kishikawakatsumi/KeychainAccess.git'
  pod 'OAuthSwift',     branch: 'swift3.0',   git: 'https://github.com/skedgo/OAuthSwift.git'

end

target 'TripKit' do
  shared_pods
end

target 'TripKitTests' do
  shared_pods
  
  pod 'RxBlocking',    branch: 'swift-3.0',  git: 'https://github.com/ReactiveX/RxSwift.git'
  pod 'RxTests',       branch: 'swift-3.0',  git: 'https://github.com/ReactiveX/RxSwift.git'
end
