source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/skedgo/PodSpecs.git'

use_frameworks!
platform :ios, '8.0'

def shared_pods
  pod 'SGCoreKit/Core', git: 'https://github.com/skedgo/shared-ios.git', branch: 'feature/SwiftyCore'
  pod 'SGCoreKit/Rx',   git: 'https://github.com/skedgo/shared-ios.git', branch: 'feature/SwiftyCore'
  pod 'SGSearchKit',    git: 'https://github.com/skedgo/shared-ios.git', branch: 'feature/SwiftyCore'
  pod 'SGCoreUIKit',    git: 'https://github.com/skedgo/shared-ios.git', branch: 'feature/SwiftyCore'
  pod 'SGUIKit',        git: 'https://github.com/skedgo/shared-ios.git', branch: 'feature/SwiftyCore'
  pod 'SGBookingKit',   git: 'https://github.com/skedgo/shared-ios.git', branch: 'feature/SwiftyCore'
  
  pod 'RxSwift',        '~> 3.0'
  pod 'RxCocoa',        '~> 3.0'
  pod 'Marshal'

  pod 'AFNetworking'
  pod 'SGPulsingAnnotationView'
end

target 'TripKit' do
  shared_pods
end

target 'TripKitTests' do
  shared_pods
  
  pod 'RxBlocking',     '~> 3.0'
  pod 'RxTest',         '~> 3.0'
end
