author: SkedGo
author_url: https://skedgo.com
title: SkedGo's TripKit iOS - TripKitUI iOS
theme: fullwidth
output: TripKitUI

module: TripKitUI
podspec: ../TripKitUI.podspec

custom_categories:
  - name: Trip Planning
    children:
      - TKUIRoutingResultsViewController
      - TKUIRoutingResultsViewControllerDelegate
      - TKUIRoutingResultsCard
      - TKUIRoutingResultsCardDelegate
      - TKUIRoutingQueryInputCard
      - TKUIRoutingQueryInputCardDelegate
      - TKUITripOverviewCard
      - TKUITripModeByModeViewController
      - TKUITripModeByModeViewControllerDelegate
      - TKUITripModeByModeCard
      - TKUITripModeByModeCardDelegate
      - TKUITripModeByModePageBuilder
  - name: Timetables
    children:
      - TKUITimetableViewController
      - TKUITimetableViewControllerDelegate
      - TKUITimetableCard
      - TKUITimetableCardAction
      - TKUITimetableCardDelegate
      - TKUIServiceCard
  - name: Search
    children:
      - TKUIAutocompletionViewController
      - TKUIAutocompletionViewControllerDelegate
