name: Swift

on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_docs:
    name: Build and deploy docs
    runs-on: macos-11
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Build docs
        run: |
          brew install sourcekitten
          cd Scripts
          ./docs.sh

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN: ios.developer.tripgo.com