name: Build docs

on:
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_docs:
    name: Build docs
    runs-on: macos-12
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Prepare dependencies
        run: |
          brew install sourcekitten
          python3 --version
          pip3 install --upgrade pip
          pip3 install mkdocs
          pip3 install pymdown-extensions     

      - name: Build docs
        run: |
          cd Scripts
          ./docs.sh
