name: Build docs

on:
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_docs:
    name: Build docs
    runs-on: macos-15
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Prepare dependencies
        run: |
          brew install sourcekitten
          python --version
          pip install --upgrade pip
          pip install mkdocs
          pip install pymdown-extensions    
          mkdocs --version 
          bundle install

      - name: Build docs
        run: |
          cd Scripts
          ./docs.sh
